[package]
name = "pixoo-bridge"
authors = ["simplyroba"]
version = "0.1.0"
edition = "2024"
license-file = "LICENSE"
description = "Lightweight bridge implentation to communicate easily with a network enabled pixoo LED dot matrix."

[dependencies]
image = "0.25.6"
axum = "0.8.4"
tokio = { version = "1.45.1", features = ["full"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tower = "0.5.2"
base64 = "0.22.1"